### ISSUE TITLE
insight-face-paddle针对不在索引库中的人没有识别出人脸

### ISSUE THREAD

**Issue by liuyang77886** [littletomatodonkey/insight-face-paddle#19]
执行以下命令
 
insightfacepaddle --det --rec --index ./demo/friends/index.bin --input ./demo/friends/query/tmp.jpg --output ./output

我想达到效果：没有在索引库中的人被识别出人脸并锚框并提示未知，在索引库中的人被识别出人脸并锚框并提示人名，请问这个能做到吗，如何做呢

**Comment by littletomatodonkey** [comment]
你好，确实是的，人脸识别是需要索引库的，需要根据自己的场景构建索引库的哈，否则确实会无法识别的

**Comment by liuyang77886** [comment]
我想达到效果：没有在索引库中的人被识别出人脸并锚框并提示未知，在索引库中的人被识别出人脸并锚框并提示人名，请问这个能做到吗，如何做呢

**Comment by littletomatodonkey** [comment]
https://github.com/littletomatodonkey/insight-face-paddle/blob/6f97c9184ccb53fa6f26d1edbbe251ef9a0ca9ad/insightface_paddle.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L759

**Comment by littletomatodonkey** [comment]
下载最新的代码，编译，安装whl包就ok了，目前代码已经支持了哈
