### ISSUE TITLE
缺少未设定参数时的判断

### ISSUE THREAD

**Issue by mikeshi80** [littletomatodonkey/insight-face-paddle#8]
https://github.com/littletomatodonkey/insight-face-paddle/blob/37f4b7db4158c1c43fb8569837a06a552fc05565/insightface_paddle.py#L631

当`index`未指定时，`args.index`为`None`，直接执行`os.path.isfile(args.index)`会触发异常：

> Traceback (most recent call last):
>   File "/home/mikeshi/test/face_recog_paddle/venv/bin/insightfacepaddle", line 8, in <module>
>     sys.exit(main())
>   File "/home/mikeshi/test/face_recog_paddle/venv/lib/python3.7/site-packages/insightface_paddle/insightface_paddle.py", line 786, in main
>     predictor = InsightFace(args)
>   File "/home/mikeshi/test/face_recog_paddle/venv/lib/python3.7/site-packages/insightface_paddle/insightface_paddle.py", line 631, in __init__
>     if not (args.build_index or os.path.isfile(args.index)):
>   File "/usr/lib/python3.7/genericpath.py", line 30, in isfile
>     st = os.stat(path)
> TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，我们这就修复下~

**Comment by TingquanGao** [comment]
感谢反馈，该问题已修复：

https://github.com/littletomatodonkey/insight-face-paddle/pull/10
